package de.vlaorgatu.vlabackend.entities.vladb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Represents an appointment in our calendar.
 */
@Data
@Entity
@Table(name = "appointments")
public class Appointment {

    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Appointment series this appointment belongs to.
     */
    @ManyToOne(optional = false)
    private AppointmentSeries series;

    /**
     * Start time of the appointment.
     */
    @Column(name = "start_time", nullable = false)
    private LocalDateTime startTime;

    /**
     * End time of the appointment.
     */
    @Column(name = "end_time", nullable = false)
    private LocalDateTime endTime;

    /**
     * Notes for this appointment.
     */
    @Column(name = "notes", nullable = false)
    private String notes = "";

    // Getters and setters generated by Lombok @Data annotation.
}
