package de.vlaorgatu.vlabackend.entities.vladb;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an appointment in our calendar.
 */
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
@Entity
@Table(name = "appointments")
public class Appointment {

    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Appointment series this appointment belongs to.
     */
    @ManyToOne(optional = false)
    private AppointmentSeries series;

    /**
     * Start time of the appointment.
     */
    @Column(name = "start_time", nullable = false)
    private LocalDateTime start;

    /**
     * End time of the appointment.
     */
    @Column(name = "end_time", nullable = false)
    private LocalDateTime end;

    /**
     * Notes for this appointment.
     */
    @Column(name = "notes", nullable = false)
    private String notes = "";

    /**
     * All VLA bookings referencing this appointment.
     */
    @OneToMany(mappedBy = "appointment", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<ExperimentBooking> bookings;

    // Getters and setters generated by Lombok @Data annotation.
}
