package de.vlaorgatu.vlabackend.entities.vladb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a lecture in a certain semester. For example "Physik I, WS 25/26".
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "lectures")
public class Lecture {
    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;  // may not be final, see https://stackoverflow.com/a/76986804

    /**
     * name of the lecture, e.g. "Physik I"
     */
    @Column(name = "name", nullable = false)
    private String name = "";

    /**
     * semester of the lecture, e.g. "WS 25/26"
     */
    @Column(name = "semester", nullable = false)
    private String semester = "";

    /**
     * Color to represent appointments in the calendar view, RGB string with # and 6 chars.
     * E.g. "#ffff00".
     */
    @Column(name = "color", nullable = false)
    private String color = "";

    /**
     * People conducting this lecture.
     */
    @ManyToMany()
    @JoinTable(
        name = "lecture_persons",
        joinColumns = @JoinColumn(name = "lecture_id"),
        inverseJoinColumns = @JoinColumn(name = "person_id"))
    private Set<Person> persons = Set.of();

    // getters and setters generated by Lombok @Data annotation
}
