package de.vlaorgatu.vlabackend.entities.vladb;

import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a person, that e.g. holds a lecture, in our calendar.
 */
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "persons")
public class Person {
    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Name of this person.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Email address to contact this person.
     */
    @Column(name = "email", nullable = false)
    private String email = "";

    /**
     * Personal notes, specifying e.g. equipment preferences of this lecturer.
     */
    @Column(name = "notes", nullable = false)
    private String notes = "";

    /**
     * ID of this user in Linus, if a corresponding user exists there.
     */
    @Column(name = "linus_user_id")
    @Nullable
    private Long linusUserId;

    /**
     * Lectures held by this person.
     */
    @ManyToMany(mappedBy = "persons")
    private Set<Lecture> lectures = Set.of();

    // Getters and setters generated by Lombok @Data annotation.

    /**
     * Custom setter for linus user ID. Converts 0 to null.
     *
     * @param linusUserId ID of this user in Linus, if a corresponding user exists there.
     */
    public void setLinusUserId(Long linusUserId) {
        this.linusUserId = linusUserId == 0 ? null : linusUserId;
    }
}
