package de.vlaorgatu.vlabackend.entities.vladb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Represents a person, that e.g. holds a lecture, in our calendar.
 */
@Data
@Entity
@Table(name = "persons")
public class Person {
    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Name of this person.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Personal notes, specifying e.g. equipment preferences of this lecturer.
     */
    @Column(name = "notes", nullable = false)
    private String notes = "";

    /**
     * ID of this user in Linus, if a corresponding user exists there.
     */
    @Column(name = "linus_user_id")
    private Long linusUserId;

    // Getters and setters generated by Lombok @Data annotation.
}
