package de.vlaorgatu.vlabackend.entities.vladb;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Represents a user in the system.
 */
@Data
@Entity
@Table(name = "users")
public class User {

    /**
     * Primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the user.
     */
    @Column(name = "name", unique = true)
    private String name;

    /**
     * Email address of the user.
     */
    @Column(name = "email", unique = true)
    private String email;

    /**
     * Represents the *hashed* password of the user.
     */
    @Column(name = "password")
    private String password;

    // Getters and setters generated by Lombok @Data annotation.
}
