package de.vlaorgatu.vlabackend.calendar.appointmentcategory;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a certain kind of appointment. Examples: vacation, lecture.
 * <br>
 * This is an own entity type (instead of just an attribute of appointment) to allow filtering
 * in the frontend.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor(force = true)
@Entity
@Table(name = "appointment_categories")
public class AppointmentCategory {
    /**
     * Primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private final Long id;

    /**
     * Name of the category.
     */
    @Column(name = "title", nullable = false)
    private String title = "";

    // getters and setters generated by Lombok @Data annotation
}
