package de.vlaorgatu.vlabackend.calendar.appointmentcategory;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Represents a certain kind of appointment. Examples: vacation, lecture.
 * <br>
 * This is an own entity type (instead of just an attribute of appointment) to allow filtering
 * in the frontend.
 */
@Data
@Entity
@Table(name = "appointment_categories")
public class AppointmentCategory {
    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Name of the category.
     */
    @Column(name = "title", unique = true, nullable = false)
    private String title = "";

    // Getters and setters generated by Lombok @Data annotation.
}
