package de.vlaorgatu.vlabackend.controller.vladb;

import de.vlaorgatu.vlabackend.controller.sse.SseController;
import de.vlaorgatu.vlabackend.entities.vladb.AppointmentCategory;
import de.vlaorgatu.vlabackend.exceptions.EntityNotFoundException;
import de.vlaorgatu.vlabackend.exceptions.InvalidParameterException;
import de.vlaorgatu.vlabackend.repositories.vladb.AppointmentCategoryRepository;
import java.util.Objects;
import lombok.AllArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Overrides to the default REST handlers generated by Spring Data REST.
 * The override is needed mainly to trigger SSE events on update operations.
 */
@AllArgsConstructor
@RestController
@RequestMapping("/api/appointmentCategories")
public class AppointmentCategoryController
    implements GetAndGetByIdDefaultInterface<AppointmentCategory, AppointmentCategoryRepository> {
    /**
     * Repository used for appointment category persistence operations.
     */
    private final AppointmentCategoryRepository appointmentCategoryRepository;

    /**
     * Creates a new appointment category.
     *
     * @param appointmentCategory The dataset for creation. Must not contain an ID (auto-generated).
     * @return OK response with the created appointment category, Error response otherwise.
     */
    @PostMapping
    public ResponseEntity<?> createAppointmentCategory(
        @RequestBody AppointmentCategory appointmentCategory) {
        if (Objects.nonNull(appointmentCategory.getId())) {
            throw new InvalidParameterException(
                "Received appointment category with ID " + appointmentCategory.getId() +
                    " when creating a new appointment category.");
        }

        AppointmentCategory savedAppointmentCategory =
            appointmentCategoryRepository.save(appointmentCategory);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Appointment category created: " + savedAppointmentCategory);
        return ResponseEntity.ok(savedAppointmentCategory);
    }

    /**
     * Updates an existing appointment category.
     *
     * @param id                  ID of the appointment category to update.
     * @param appointmentCategory Dataset of the appointment category to update.
     *                            Must contain all keys, ID may be omitted.
     * @return OK response with the updated appointment category, Error response otherwise.
     */
    @PutMapping("/{id}")
    public ResponseEntity<?> updateAppointmentCategory(
        @PathVariable Long id, @RequestBody AppointmentCategory appointmentCategory
    ) {
        if (Objects.isNull(appointmentCategory.getId())) {
            appointmentCategory.setId(id);
        } else if (!appointmentCategory.getId().equals(id)) {
            throw new InvalidParameterException(
                "Received inconsistent IDs on appointment category modification. ID from url: " +
                    id + " vs. ID from body data: " + appointmentCategory.getId() + ".");
        }
        if (!appointmentCategoryRepository.existsById(id)) {
            throw new EntityNotFoundException(
                "Appointment category with ID " + id + " not found.");
        }

        AppointmentCategory updatedAppointmentCategory =
            appointmentCategoryRepository.save(appointmentCategory);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest(
            "Appointment category updated: " + updatedAppointmentCategory);
        return ResponseEntity.ok(updatedAppointmentCategory);
    }

    /**
     * Deletes an appointment category by its ID.
     *
     * @param id ID of the appointment category to delete.
     * @return OK response with the deleted appointment category, Error response otherwise.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<?> deleteAppointmentCategory(@PathVariable Long id) {
        AppointmentCategory deletedAppointmentCategory = appointmentCategoryRepository.findById(id)
            .orElseThrow(() -> new EntityNotFoundException(
                "Appointment category with ID " + id + " not found."));
        appointmentCategoryRepository.deleteById(id);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest(
            "Appointment category deleted: " + deletedAppointmentCategory);
        return ResponseEntity.ok(deletedAppointmentCategory);
    }
}
