package de.vlaorgatu.vlabackend.controller.vladb;

import de.vlaorgatu.vlabackend.controller.sse.SseController;
import de.vlaorgatu.vlabackend.entities.vladb.AppointmentSeries;
import de.vlaorgatu.vlabackend.enums.sse.SseMessageType;
import de.vlaorgatu.vlabackend.exceptions.EntityNotFoundException;
import de.vlaorgatu.vlabackend.exceptions.InvalidParameterException;
import de.vlaorgatu.vlabackend.repositories.vladb.AppointmentSeriesRepository;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import lombok.AllArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Overrides to the default REST handlers generated by Spring Data REST.
 * <br>
 * Mainly needed to trigger SSE events on update operations.
 */
@AllArgsConstructor
@RestController
@RequestMapping("/api/appointmentSeries")
public class AppointmentSeriesController
    implements
    DefaultGettingForJpaReposInterface<AppointmentSeries, AppointmentSeriesRepository> {
    /**
     * Repository used for appointment series persistence operations.
     */
    private final AppointmentSeriesRepository appointmentSeriesRepository;

    /**
     * Creates a new appointment series.
     *
     * @param appointmentSeries The dataset for creation. Must not contain an ID (auto-generated).
     * @return OK response with the created appointment series, Error response otherwise.
     */
    @PostMapping
    public ResponseEntity<AppointmentSeries> createAppointmentSeries(
        @RequestBody AppointmentSeries appointmentSeries) {
        if (Objects.nonNull(appointmentSeries.getId())) {
            if (appointmentSeries.getId() < 0) {
                appointmentSeries.setId(null);
            } else {
                throw new InvalidParameterException(
                    "Received appointment series with ID " + appointmentSeries.getId() +
                        " when creating a new appointment series.");
            }
        }

        AppointmentSeries saved = appointmentSeriesRepository.save(appointmentSeries);
        SseController.notifyAllOfObject(SseMessageType.APPOINTMENTSERIESCREATED, saved);
        return ResponseEntity.ok(saved);
    }

    /**
     * Creates multiple appointment series.
     *
     * @param appointmentSeries List of datasets for creation.
     * @return OK response with the created appointment series list, Error response otherwise.
     */
    @PostMapping("/multi")
    public ResponseEntity<AppointmentSeries[]> createAppointmentSeriesMulti(
        @RequestBody AppointmentSeries[] appointmentSeries) {
        if (Arrays.stream(appointmentSeries)
            .map(AppointmentSeries::getId)
            .filter(Objects::nonNull)
            .anyMatch(id -> id > 0)
        ) {
            throw new InvalidParameterException(
                "Received appointment series with ID > 0 when bulk-creating appointment series.");
        }
        Arrays.stream(appointmentSeries).forEach((series) -> {
            series.setId(null);
        });

        List<AppointmentSeries> saved =
            appointmentSeriesRepository.saveAll(Arrays.asList(appointmentSeries));
        saved.forEach((series) -> {
            SseController.notifyAllOfObject(SseMessageType.APPOINTMENTSERIESCREATED, series);
        });
        return ResponseEntity.ok(saved.toArray(AppointmentSeries[]::new));
    }

    /**
     * Updates an existing appointment series.
     *
     * @param id                ID of the appointment series to update.
     * @param appointmentSeries Dataset of the appointment series to update.
     *                          Must contain all keys, ID may be omitted.
     * @return OK response with the updated appointment series, Error response otherwise.
     */
    @PutMapping("/{id}")
    public ResponseEntity<AppointmentSeries> updateAppointmentSeries(
        @PathVariable Long id, @RequestBody AppointmentSeries appointmentSeries
    ) {
        if (Objects.isNull(appointmentSeries.getId())) {
            appointmentSeries.setId(id);
        } else if (!appointmentSeries.getId().equals(id)) {
            throw new InvalidParameterException(
                "Received inconsistent IDs on appointment series update. ID from url: " + id +
                    " vs. ID from body data: " + appointmentSeries.getId() + ".");
        }
        if (!appointmentSeriesRepository.existsById(id)) {
            throw new EntityNotFoundException(
                "Appointment series with ID " + id + " not found.");
        }

        AppointmentSeries updated = appointmentSeriesRepository.save(appointmentSeries);
        SseController.notifyAllOfObject(SseMessageType.APPOINTMENTSERIESUPDATED, updated);
        return ResponseEntity.ok(updated);
    }

    /**
     * Deletes an appointment series by its ID.
     *
     * @param id ID of the appointment series to delete.
     * @return OK response with the deleted dataset.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<AppointmentSeries> deleteAppointmentSeries(@PathVariable Long id) {
        AppointmentSeries deletedAppointmentSeries = appointmentSeriesRepository.findById(id)
            .orElseThrow(() -> new EntityNotFoundException(
                "Appointment series with ID " + id + " not found."));

        appointmentSeriesRepository.deleteById(id);
        SseController.notifyAllOfObject(SseMessageType.APPOINTMENTSERIESDELETED,
            deletedAppointmentSeries);
        return ResponseEntity.ok(deletedAppointmentSeries);
    }

    /**
     * Retrieves the repository ot this controller instance.
     *
     * @return The JPARepository used by this controller
     */
    @Override
    public AppointmentSeriesRepository getRepository() {
        return appointmentSeriesRepository;
    }
}
