package de.vlaorgatu.vlabackend.controller.vladb;

import de.vlaorgatu.vlabackend.controller.sse.SseController;
import de.vlaorgatu.vlabackend.entities.vladb.AppointmentSeries;
import de.vlaorgatu.vlabackend.exceptions.EntityNotFoundException;
import de.vlaorgatu.vlabackend.exceptions.InvalidParameterException;
import de.vlaorgatu.vlabackend.repositories.vladb.AppointmentSeriesRepository;
import java.util.Objects;
import lombok.AllArgsConstructor;
import org.springframework.data.rest.webmvc.RepositoryRestController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

/**
 * Overrides to the default REST handlers generated by Spring Data REST.
 * <br>
 * Mainly needed to trigger SSE events on update operations.
 */
@AllArgsConstructor
@RepositoryRestController
public class AppointmentSeriesController {
    /**
     * Repository used for appointment series persistence operations.
     */
    private final AppointmentSeriesRepository appointmentSeriesRepository;

    /**
     * Creates a new appointment series.
     *
     * @param appointmentSeries The dataset for creation. Must not contain an ID (auto-generated).
     * @return OK response with the created appointment series, Error response otherwise.
     */
    @PostMapping("/appointmentSeries")
    public ResponseEntity<?> createAppointmentSeries(
        @RequestBody AppointmentSeries appointmentSeries) {
        if (Objects.nonNull(appointmentSeries.getId())) {
            throw new InvalidParameterException(
                "Received appointment series with ID " + appointmentSeries.getId() +
                    " when creating a new appointment series.");
        }

        AppointmentSeries saved = appointmentSeriesRepository.save(appointmentSeries);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Appointment series created: " + saved);
        return ResponseEntity.ok(saved);
    }

    /**
     * Updates an existing appointment series.
     *
     * @param id                ID of the appointment series to update.
     * @param appointmentSeries Dataset of the appointment series to update.
     *                          Must contain all keys, ID may be omitted.
     * @return OK response with the updated appointment series, Error response otherwise.
     */
    @PutMapping("/appointmentSeries/{id}")
    public ResponseEntity<?> updateAppointmentSeries(
        @PathVariable Long id, @RequestBody AppointmentSeries appointmentSeries
    ) {
        if (Objects.isNull(appointmentSeries.getId())) {
            appointmentSeries.setId(id);
        } else if (!appointmentSeries.getId().equals(id)) {
            throw new InvalidParameterException(
                "Received inconsistent IDs on appointment series update. ID from url: " + id +
                    " vs. ID from body data: " + appointmentSeries.getId() + ".");
        }
        if (!appointmentSeriesRepository.existsById(id)) {
            throw new EntityNotFoundException(
                "Appointment series with ID " + id + " not found for update.");
        }

        AppointmentSeries updated = appointmentSeriesRepository.save(appointmentSeries);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Appointment series updated: " + updated);
        return ResponseEntity.ok(updated);
    }

    /**
     * Deletes an appointment series by its ID.
     *
     * @param id ID of the appointment series to delete.
     * @return OK response with the deleted dataset.
     */
    @DeleteMapping("/appointmentSeries/{id}")
    public ResponseEntity<?> deleteAppointmentSeries(@PathVariable Long id) {
        AppointmentSeries deletedAppointmentSeries = appointmentSeriesRepository.findById(id)
            .orElseThrow(() -> new EntityNotFoundException(
                "Appointment series with ID " + id + " not found for deletion."));

        appointmentSeriesRepository.deleteById(id);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Appointment series deleted: " + deletedAppointmentSeries);
        return ResponseEntity.ok(deletedAppointmentSeries);
    }
}
