package de.vlaorgatu.vlabackend.calendar.person;

import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

import de.vlaorgatu.vlabackend.sse.SseController;
import java.util.Objects;
import java.util.Optional;
import lombok.AllArgsConstructor;
import org.slf4j.Logger;
import org.springframework.data.rest.webmvc.RepositoryRestController;
import org.springframework.hateoas.EntityModel;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

/**
 * Overrides to the default REST handlers generated by Spring Data REST.
 * The override is needed mainly to trigger SSE events on update operations.
 */
@AllArgsConstructor
@RepositoryRestController
public class PersonController {

    private static final Logger LOGGER = org.slf4j.LoggerFactory.getLogger(PersonController.class);
    private final PersonRepository personRepository;

    /**
     * A new person was born.
     *
     * @param person Dataset of the person to create.
     * @return       OK response with the created person, Error response otherwise.
     */
    @PostMapping("/persons")
    public ResponseEntity<?> createPerson(@RequestBody Person person) {
        if (Objects.nonNull(person.getId())) {
            LOGGER.warn("Received person with ID {} when creating a new person.", person.getId());
            return ResponseEntity.badRequest().build();
        }

        Person savedPerson = personRepository.save(person);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Person created: " + savedPerson);

        EntityModel<Person> personModel = EntityModel.of(savedPerson, linkTo(
            methodOn(PersonController.class).updatePerson(person.getId(), person)).withSelfRel());
        return ResponseEntity.ok(personModel);
    }

    /**
     * Updates an existing person.
     *
     * @param id     ID of the person to update
     * @param person dataset for update. Must contain all keys, ID may be omitted.
     * @return       OK response with updated person, Error response otherwise.
     */
    @PutMapping("/persons/{id}")
    public ResponseEntity<?> updatePerson(@PathVariable Long id, @RequestBody Person person) {
        if (Objects.isNull(person.getId())) {
            person.setId(id);
        } else if (!person.getId().equals(id)) {
            LOGGER.warn("Received inconsistent IDs on person modification." +
                " ID from url: {} vs. ID from body data: {}.", id, person.getId());
            return ResponseEntity.badRequest().build();
        }
        if (!personRepository.existsById(id)) {
            LOGGER.warn("Received person update for non-existing person with ID {}.", id);
            return ResponseEntity.notFound().build();
        }

        Person updatedPerson = personRepository.save(person);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Person updated: " + updatedPerson);

        EntityModel<Person> personModel = EntityModel.of(updatedPerson,
            linkTo(methodOn(PersonController.class).updatePerson(id, person)).withSelfRel());
        return ResponseEntity.ok(personModel);
    }

    /**
     * Deletes a person by its ID.
     *
     * @param id ID of the person to delete
     * @return   OK response with deleted person, Error response otherwise.
     */
    @DeleteMapping("/persons/{id}")
    public ResponseEntity<?> deletePerson(@PathVariable Long id) {
        Optional<Person> personOptional = personRepository.findById(id);
        if (personOptional.isEmpty()) {
            LOGGER.warn("Received person deletion for non-existing person with ID {}.", id);
            return ResponseEntity.notFound().build();
        }

        personRepository.deleteById(id);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Person deleted: " + personOptional.get());

        EntityModel<Person> personModel = EntityModel.of(personOptional.get(),
            linkTo(methodOn(PersonController.class).deletePerson(id)).withSelfRel());
        return ResponseEntity.ok(personModel);
    }
}
