package de.vlaorgatu.vlabackend.calendar.appointmentseries;

import de.vlaorgatu.vlabackend.calendar.appointmentcategory.AppointmentCategory;
import de.vlaorgatu.vlabackend.calendar.lecture.Lecture;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Represents a series of appointments for a certain lecture.
 * <br>
 * Example: Physik 1 WS25/26 Donnerstags (where Physik 1 WS25/26 is a lecture)
 */
@Data
@Entity
@Table(name = "appointment_series")
public class AppointmentSeries {

    /**
     * Primary key.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Lecture this series belongs to.
     */
    @ManyToOne
    private Lecture lecture;

    /**
     * Appointment category of this series.
     */
    @ManyToOne
    private AppointmentCategory category;

    // Getters and setters generated by Lombok @Data annotation.
}
