package de.vlaorgatu.vlabackend.calendar.lecture;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a lecture in a certain semester. For example "Physik I, WS 25/26".
 */
@Data
@AllArgsConstructor
@NoArgsConstructor(force = true)
@Entity
@Table(name = "lectures")
class Lecture {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private final Long id;

    /**
     * title of the lecture, e.g. "Physik I"
     */
    @Column(name = "title", nullable = false)
    private String title = "";

    /**
     * semester of the lecture, e.g. "WS 25/26"
     */
    @Column(name = "semester", nullable = false)
    private String semester = "";

    /**
     * Color to represent appointments in the calendar view, RGB string.
     */
    @Column(name = "color", nullable = false)
    private String color = "";

    // getters and setters generated by Lombok @Data annotation
}
