CREATE TABLE global_notes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note_color VARCHAR(255)                            NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    VARCHAR(4096)                           NOT NULL,
    CONSTRAINT pk_globalnotes PRIMARY KEY (id)
);