ALTER TABLE experiment_bookings
DROP
CONSTRAINT fk_experiment_bookings_on_appointment;

CREATE TABLE global_notes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note_color VARCHAR(255)                            NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    VARCHAR(4096)                           NOT NULL,
    CONSTRAINT pk_globalnotes PRIMARY KEY (id)
);

ALTER TABLE appointments
    ADD end_time TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE appointments
    ADD start_time TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE appointments
    ALTER COLUMN end_time SET NOT NULL;

ALTER TABLE appointments
    ALTER COLUMN start_time SET NOT NULL;

ALTER TABLE appointments
DROP
COLUMN "end";

ALTER TABLE appointments
DROP
COLUMN start;

ALTER TABLE experiment_bookings
    ALTER COLUMN appointment_id SET NOT NULL;