package de.vlaorgatu.vlabackend.entities.calendar.appointmentcategory;

import de.vlaorgatu.vlabackend.sse.SseController;
import java.util.Objects;
import java.util.Optional;
import lombok.AllArgsConstructor;
import org.slf4j.Logger;
import org.springframework.data.rest.webmvc.RepositoryRestController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

/**
 * Overrides to the default REST handlers generated by Spring Data REST.
 * The override is needed mainly to trigger SSE events on update operations.
 */
@AllArgsConstructor
@RepositoryRestController
public class AppointmentCategoryController {
    private static final Logger LOGGER =
        org.slf4j.LoggerFactory.getLogger(AppointmentCategoryController.class);
    private final AppointmentCategoryRepository appointmentCategoryRepository;

    /**
     * Creates a new appointment category.
     *
     * @param appointmentCategory The dataset for creation. Must not contain an ID.
     * @return OK response with the created appointment category, Error response otherwise.
     */
    @PostMapping("/appointmentCategories")
    public ResponseEntity<?> createAppointmentCategory(
        @RequestBody AppointmentCategory appointmentCategory) {
        if (Objects.nonNull(appointmentCategory.getId())) {
            LOGGER.warn("Received appointment category with ID {} when creating" +
                " a new appointment category.", appointmentCategory.getId());
            return ResponseEntity.badRequest().build();
        }

        AppointmentCategory savedAppointmentCategory =
            appointmentCategoryRepository.save(appointmentCategory);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest("Appointment category created: " + savedAppointmentCategory);
        return ResponseEntity.ok(savedAppointmentCategory);
    }

    /**
     * Updates an existing appointment category.
     *
     * @param id                  ID of the appointment category to update.
     * @param appointmentCategory Dataset of the appointment category to update.
     *                            Must contain all keys, ID may be omitted.
     * @return OK response with the updated appointment category, Error response otherwise.
     */
    @PutMapping("/appointmentCategory/{id}")
    public ResponseEntity<?> updateAppointmentCategory(
        @PathVariable Long id, @RequestBody AppointmentCategory appointmentCategory) {
        if (Objects.isNull(appointmentCategory.getId())) {
            appointmentCategory.setId(id);
        } else if (!appointmentCategory.getId().equals(id)) {
            LOGGER.warn("Received inconsistent IDs on appointment category modification." +
                " ID from url: {} vs. ID from body data: {}.", id, appointmentCategory.getId());
            return ResponseEntity.badRequest().build();
        }
        if (!appointmentCategoryRepository.existsById(id)) {
            LOGGER.warn("Received appointment category update for non-existing" +
                " appointment category with ID {}.", id);
            return ResponseEntity.notFound().build();
        }

        AppointmentCategory updatedAppointmentCategory =
            appointmentCategoryRepository.save(appointmentCategory);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest(
            "Appointment category updated: " + updatedAppointmentCategory);
        return ResponseEntity.ok(updatedAppointmentCategory);
    }

    /**
     * Deletes an appointment category by its ID.
     *
     * @param id ID of the appointment category to delete.
     * @return OK response with the deleted appointment category, Error response otherwise.
     */
    @DeleteMapping("/appointmentCategory/{id}")
    public ResponseEntity<?> deleteAppointmentCategory(@PathVariable Long id) {
        Optional<AppointmentCategory> appointmentCategoryOptional =
            appointmentCategoryRepository.findById(id);
        if (appointmentCategoryOptional.isEmpty()) {
            LOGGER.warn("Received appointment category deletion for non-existing" +
                " appointment category with ID {}.", id);
            return ResponseEntity.notFound().build();
        }

        appointmentCategoryRepository.deleteById(id);
        // TODO: use a better method here instead of debug message
        SseController.notifyDebugTest(
            "Appointment category deleted: " + appointmentCategoryOptional.get());
        return ResponseEntity.ok(appointmentCategoryOptional.get());
    }
}
